import os
import shutil
import pandas as pd

testmode = False
random_ints = [678, 147, 561, 237, 588, 951, 490, 395, 877, 297, 721, 711, 985, 171, 75, 16, 669, 530, 999, 794, 936, 111, 816, 968, 48, 986, 829, 996, 272, 759, 390, 930, 633, 928, 854, 554, 562, 78, 222, 294, 725, 582, 731, 249, 791, 35, 180, 510, 593, 634]

testsizes = [0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95]

cwd = os.getcwd()
datasetfiles = [os.path.join(cwd, 'CLEANED_gridsearch_1296.csv'), os.path.join(cwd, 'CLEANED_gridsearch_2401.csv'), os.path.join(cwd, 'CLEANED_sobolsampling-2048.csv'), os.path.join(cwd, 'CLEANED_sobolsampling-2048-2.csv')]

### create current working directory ###
cwd = os.path.join(cwd, "diffKernels_trained_GPModels")
#print(f'{cwd}')
if os.path.exists(cwd):
  if testmode:
    shutil.rmtree(cwd)
  else:
    print(f'\nPATH \'{cwd}\' already exists. \n\nExiting without starting or changing anything.\n')
    exit()

os.mkdir(cwd)


### read datasets ###
## grid sampling 1296
#data1296 = pd.read_csv('CLEANED_gridsearch_1296.csv')
#data1296 = data1296.drop(data1296.columns[0], axis=1)
#X_1296 = data1296.drop('density', axis=1)
#Y_1296 = data1296['density']
## grid sampling 2401
#data2401 = pd.read_csv('CLEANED_gridsearch_2401.csv')
#data2401 = data2401.drop(data2401.columns[0], axis=1)
#X_2401 = data2401.drop('density', axis=1)
#Y_2401 = data2401['density']
## sobol2 sampling
#data_sobol1 = pd.read_csv('CLEANED_sobolsampling-2048.csv')
#data_sobol1 = data_sobol1.drop(data_sobol1.columns[0], axis=1)
#X_sobol1 = data_sobol1.drop('density', axis=1)
#Y_sobol1 = data_sobol1['density']
## sobol2 sampling
#data_sobol2 = pd.read_csv('CLEANED_sobolsampling-2048-2.csv')
#data_sobol2 = data_sobol2.drop(data_sobol2.columns[0], axis=1)
#X_sobol2 = data_sobol2.drop('density', axis=1)
#Y_sobol2 = data_sobol2['density']


def create_batch_file(tmp_cwd, rnd_int, ratio, thisPythonFile):
  fileName = f'batch_start_training_{rnd_int}.sh'
  batchFile = os.path.join(tmp_cwd, fileName)
  
  if os.path.exists(batchFile):
    os.remove(batchFile)
  
  f = open(batchFile, 'w')
  f.write(f'#!/bin/bash\n')
  f.write(f'#SBATCH --partition=hpc,hpc1,hpc3\n')
  f.write(f'#SBATCH --nodes=1\n')
  f.write(f'#SBATCH --mem 10G\n')
  f.write(f'#SBATCH --time=15:00:00\n')
  f.write(f'#SBATCH --job-name={ratio}-{rnd_int}\n')
  f.write(f'\n')
  f.write(f'python {thisPythonFile}\n')
  f.close()
  
  return os.path.basename(batchFile)


def copy_datasetfiles(tmp_cwd, datasetfiles):
  tmp_datasetfiles = []
  for datasetfile in datasetfiles:
    tmp_datasetfile = os.path.join(tmp_cwd, os.path.basename(datasetfile))
    #print(f'{tmp_datasetfile}')
    if os.path.exists(tmp_datasetfile):
      os.remove(tmp_datasetfile)
    shutil.copy(datasetfile, tmp_datasetfile)
    tmp_datasetfiles.append(os.path.basename(tmp_datasetfile))

  return tmp_datasetfiles


def create_python_file(tmp_cwd, rnd_int, ratio, tmp_datasetfiles):
  fileName = f'train_{ratio}_{rnd_int}.py'
  thisPythonFile = os.path.join(tmp_cwd, fileName)
  
  if os.path.exists(thisPythonFile):
    os.remove(thisPythonFile)
  
  f = open(thisPythonFile, 'w')
  f.write(f'### imports ###\n')
  f.write(f'from sklearn.gaussian_process import GaussianProcessRegressor\n')
  f.write(f'from sklearn.gaussian_process.kernels import RBF\n')
  f.write(f'from sklearn.gaussian_process.kernels import Matern\n')
  f.write(f'from sklearn.gaussian_process.kernels import RationalQuadratic as RQ\n')
  f.write(f'from sklearn.gaussian_process.kernels import ExpSineSquared as ESS\n')
  f.write(f'from sklearn.model_selection import train_test_split\n')
  f.write(f'from sklearn.metrics import mean_squared_error, r2_score\n')
  f.write(f'import pandas as pd\n')
  f.write(f'import numpy as np\n')
  f.write(f'from scipy import stats\n')
  f.write(f'from matplotlib import pyplot as plt\n')
  f.write(f'import time\n')
  f.write(f'import pickle\n')
  f.write(f'\n')
  f.write(f'\n')
  f.write(f'### read datasets ###\n')
  f.write(f'dataGrid1296 = pd.read_csv(\'CLEANED_gridsearch_1296.csv\')\n')
  f.write(f'dataGrid1296 = dataGrid1296.drop(dataGrid1296.columns[0], axis=1)\n')
  f.write(f'X_Grid1296 = dataGrid1296.drop(\'density\', axis=1)\n')
  f.write(f'Y_Grid1296 = dataGrid1296[\'density\']\n')
  f.write(f'\n')
  f.write(f'dataGrid2401 = pd.read_csv(\'CLEANED_gridsearch_2401.csv\')\n')
  f.write(f'dataGrid2401 = dataGrid2401.drop(dataGrid2401.columns[0], axis=1)\n')
  f.write(f'X_Grid2401 = dataGrid2401.drop(\'density\', axis=1)\n')
  f.write(f'Y_Grid2401 = dataGrid2401[\'density\']\n')
  f.write(f'\n')
  f.write(f'dataSobol1 = pd.read_csv(\'CLEANED_sobolsampling-2048.csv\')\n')
  f.write(f'dataSobol1 = dataSobol1.drop(dataSobol1.columns[0], axis=1)\n')
  f.write(f'X_Sobol1 = dataSobol1.drop(\'density\', axis=1)\n')
  f.write(f'Y_Sobol1 = dataSobol1[\'density\']\n')
  f.write(f'\n')
  f.write(f'dataSobol2 = pd.read_csv(\'CLEANED_sobolsampling-2048-2.csv\')\n')
  f.write(f'dataSobol2 = dataSobol2.drop(dataSobol2.columns[0], axis=1)\n')
  f.write(f'X_Sobol2 = dataSobol2.drop(\'density\', axis=1)\n')
  f.write(f'Y_Sobol2 = dataSobol2[\'density\']\n')
  f.write(f'\n')
  f.write(f'\n')
  f.write(f'### prepare training and testdata ###\n')
  f.write(f'X_train_Grid1296, X_test_Grid1296, Y_train_Grid1296, Y_test_Grid1296 = train_test_split(X_Grid1296, Y_Grid1296, test_size={ratio}, random_state={rnd_int})\n')
  f.write(f'X_test_Grid1296 = pd.concat([X_test_Grid1296, X_Grid2401, X_Sobol1, X_Sobol2], ignore_index=True)\n')
  f.write(f'Y_test_Grid1296 = pd.concat([Y_test_Grid1296, Y_Grid2401, Y_Sobol1, Y_Sobol2], ignore_index=True)\n')
  f.write(f'\n')
  f.write(f'X_train_Grid2401, X_test_Grid2401, Y_train_Grid2401, Y_test_Grid2401 = train_test_split(X_Grid2401, Y_Grid2401, test_size={ratio}, random_state={rnd_int})\n')
  f.write(f'X_test_Grid2401 = pd.concat([X_test_Grid2401, X_Grid1296, X_Sobol1, X_Sobol2], ignore_index=True)\n')
  f.write(f'Y_test_Grid2401 = pd.concat([Y_test_Grid2401, Y_Grid1296, Y_Sobol1, Y_Sobol2], ignore_index=True)\n')
  f.write(f'\n')
  f.write(f'X_train_Sobol1, X_test_Sobol1, Y_train_Sobol1, Y_test_Sobol1 = train_test_split(X_Sobol1, Y_Sobol1, test_size={ratio}, random_state={rnd_int})\n')
  f.write(f'X_test_Sobol1 = pd.concat([X_test_Sobol1, X_Grid1296, X_Grid2401, X_Sobol2], ignore_index=True)\n')
  f.write(f'Y_test_Sobol1 = pd.concat([Y_test_Sobol1, Y_Grid1296, Y_Grid2401, Y_Sobol2], ignore_index=True)\n')
  f.write(f'\n')
  f.write(f'X_train_Sobol2, X_test_Sobol2, Y_train_Sobol2, Y_test_Sobol2 = train_test_split(X_Sobol2, Y_Sobol2, test_size={ratio}, random_state={rnd_int})\n')
  f.write(f'X_test_Sobol2 = pd.concat([X_test_Sobol2, X_Grid1296, X_Grid2401, X_Sobol1], ignore_index=True)\n')
  f.write(f'Y_test_Sobol2 = pd.concat([Y_test_Sobol2, Y_Grid1296, Y_Grid2401, Y_Sobol1], ignore_index=True)\n')
  f.write(f'\n')
  f.write(f'\n')
  f.write(f'### train models ###\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'Training Models for Ratio: {ratio}, RndInt: {rnd_int}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'n_restarts = 9\n')
  f.write(f'kernel1 = RBF()\n')
  f.write(f'kernel2 = Matern()\n')
  f.write(f'kernel3 = RQ()\n')
  f.write(f'kernel4 = ESS()\n')
  f.write(f'model1Grid1296 = GaussianProcessRegressor(kernel=kernel1, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model2Grid1296 = GaussianProcessRegressor(kernel=kernel2, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model3Grid1296 = GaussianProcessRegressor(kernel=kernel3, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model4Grid1296 = GaussianProcessRegressor(kernel=kernel4, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'print(f\'RBF Kernel BEFORE training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f't1_Grid1296 = time.time()\n')
  f.write(f'model1Grid1296.fit(X_train_Grid1296, Y_train_Grid1296)\n')
  f.write(f'dt_Grid1296 = time.time() - t1_Grid1296\n')
  f.write(f'print(f\'RBF Kernel AFTER training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid1296, RBF Kernel: ')
  f.write('{dt_Grid1296')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'Matern Kernel BEFORE training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f't1_Grid1296 = time.time()\n')
  f.write(f'model2Grid1296.fit(X_train_Grid1296, Y_train_Grid1296)\n')
  f.write(f'dt_Grid1296 = time.time() - t1_Grid1296\n')
  f.write(f'print(f\'Matern Kernel AFTER training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid1296, Matern Kernel: ')
  f.write('{dt_Grid1296')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'RQ Kernel BEFORE training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f't1_Grid1296 = time.time()\n')
  f.write(f'model3Grid1296.fit(X_train_Grid1296, Y_train_Grid1296)\n')
  f.write(f'dt_Grid1296 = time.time() - t1_Grid1296\n')
  f.write(f'print(f\'RQ Kernel AFTER training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid1296, RQ Kernel: ')
  f.write('{dt_Grid1296')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'ESS Kernel BEFORE training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f't1_Grid1296 = time.time()\n')
  f.write(f'model4Grid1296.fit(X_train_Grid1296, Y_train_Grid1296)\n')
  f.write(f'dt_Grid1296 = time.time() - t1_Grid1296\n')
  f.write(f'print(f\'ESS Kernel AFTER training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid1296, ESS Kernel: ')
  f.write('{dt_Grid1296')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'kernel1 = RBF()\n')
  f.write(f'kernel2 = Matern()\n')
  f.write(f'kernel3 = RQ()\n')
  f.write(f'kernel4 = ESS()\n')
  f.write(f'model1Grid2401 = GaussianProcessRegressor(kernel=kernel1, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model2Grid2401 = GaussianProcessRegressor(kernel=kernel2, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model3Grid2401 = GaussianProcessRegressor(kernel=kernel3, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model4Grid2401 = GaussianProcessRegressor(kernel=kernel4, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'print(f\'RBF Kernel BEFORE training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f't1_Grid2401 = time.time()\n')
  f.write(f'model1Grid2401.fit(X_train_Grid2401, Y_train_Grid2401)\n')
  f.write(f'dt_Grid2401 = time.time() - t1_Grid2401\n')
  f.write(f'print(f\'RBF Kernel AFTER training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid2401, RBF Kernel: ')
  f.write('{dt_Grid2401')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'Matern Kernel BEFORE training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f't1_Grid2401 = time.time()\n')
  f.write(f'model2Grid2401.fit(X_train_Grid2401, Y_train_Grid2401)\n')
  f.write(f'dt_Grid2401 = time.time() - t1_Grid2401\n')
  f.write(f'print(f\'Matern Kernel AFTER training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid2401, Matern Kernel: ')
  f.write('{dt_Grid2401')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'RQ Kernel BEFORE training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f't1_Grid2401 = time.time()\n')
  f.write(f'model3Grid2401.fit(X_train_Grid2401, Y_train_Grid2401)\n')
  f.write(f'dt_Grid2401 = time.time() - t1_Grid2401\n')
  f.write(f'print(f\'RQ Kernel AFTER training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid2401, RQ Kernel: ')
  f.write('{dt_Grid2401')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'ESS Kernel BEFORE training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f't1_Grid2401 = time.time()\n')
  f.write(f'model4Grid2401.fit(X_train_Grid2401, Y_train_Grid2401)\n')
  f.write(f'dt_Grid2401 = time.time() - t1_Grid2401\n')
  f.write(f'print(f\'ESS Kernel AFTER training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Grid2401, ESS Kernel: ')
  f.write('{dt_Grid2401')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'kernel1 = RBF()\n')
  f.write(f'kernel2 = Matern()\n')
  f.write(f'kernel3 = RQ()\n')
  f.write(f'kernel4 = ESS()\n')
  f.write(f'model1Sobol1 = GaussianProcessRegressor(kernel=kernel1, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model2Sobol1 = GaussianProcessRegressor(kernel=kernel2, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model3Sobol1 = GaussianProcessRegressor(kernel=kernel3, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model4Sobol1 = GaussianProcessRegressor(kernel=kernel4, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'print(f\'RBF Kernel BEFORE training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f't1_Sobol1 = time.time()\n')
  f.write(f'model1Sobol1.fit(X_train_Sobol1, Y_train_Sobol1)\n')
  f.write(f'dt_Sobol1 = time.time() - t1_Sobol1\n')
  f.write(f'print(f\'RBF Kernel AFTER training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol1, RBF Kernel: ')
  f.write('{dt_Sobol1')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'Matern Kernel BEFORE training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f't1_Sobol1 = time.time()\n')
  f.write(f'model2Sobol1.fit(X_train_Sobol1, Y_train_Sobol1)\n')
  f.write(f'dt_Sobol1 = time.time() - t1_Sobol1\n')
  f.write(f'print(f\'Matern Kernel AFTER training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol1, Matern Kernel: ')
  f.write('{dt_Sobol1')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'RQ Kernel BEFORE training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f't1_Sobol1 = time.time()\n')
  f.write(f'model3Sobol1.fit(X_train_Sobol1, Y_train_Sobol1)\n')
  f.write(f'dt_Sobol1 = time.time() - t1_Sobol1\n')
  f.write(f'print(f\'RQ Kernel AFTER training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol1, RQ Kernel: ')
  f.write('{dt_Sobol1')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'ESS Kernel BEFORE training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f't1_Sobol1 = time.time()\n')
  f.write(f'model4Sobol1.fit(X_train_Sobol1, Y_train_Sobol1)\n')
  f.write(f'dt_Sobol1 = time.time() - t1_Sobol1\n')
  f.write(f'print(f\'ESS Kernel AFTER training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol1, ESS Kernel: ')
  f.write('{dt_Sobol1')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'kernel1 = RBF()\n')
  f.write(f'kernel2 = Matern()\n')
  f.write(f'kernel3 = RQ()\n')
  f.write(f'kernel4 = ESS()\n')
  f.write(f'model1Sobol2 = GaussianProcessRegressor(kernel=kernel1, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model2Sobol2 = GaussianProcessRegressor(kernel=kernel2, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model3Sobol2 = GaussianProcessRegressor(kernel=kernel3, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'model4Sobol2 = GaussianProcessRegressor(kernel=kernel4, n_restarts_optimizer=n_restarts, random_state={rnd_int})\n')
  f.write(f'print(f\'RBF Kernel BEFORE training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f't1_Sobol2 = time.time()\n')
  f.write(f'model1Sobol2.fit(X_train_Sobol2, Y_train_Sobol2)\n')
  f.write(f'dt_Sobol2 = time.time() - t1_Sobol2\n')
  f.write(f'print(f\'RBF Kernel AFTER training: ')
  f.write('{kernel1} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol2, RBF Kernel: ')
  f.write('{dt_Sobol2')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'Matern Kernel BEFORE training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f't1_Sobol2 = time.time()\n')
  f.write(f'model2Sobol2.fit(X_train_Sobol2, Y_train_Sobol2)\n')
  f.write(f'dt_Sobol2 = time.time() - t1_Sobol2\n')
  f.write(f'print(f\'Matern Kernel AFTER training: ')
  f.write('{kernel2} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol2, Matern Kernel: ')
  f.write('{dt_Sobol2')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'RQ Kernel BEFORE training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f't1_Sobol2 = time.time()\n')
  f.write(f'model3Sobol2.fit(X_train_Sobol2, Y_train_Sobol2)\n')
  f.write(f'dt_Sobol2 = time.time() - t1_Sobol2\n')
  f.write(f'print(f\'RQ Kernel AFTER training: ')
  f.write('{kernel3} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol2, RQ Kernel: ')
  f.write('{dt_Sobol2')
  f.write('/3600}hrs\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'ESS Kernel BEFORE training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f't1_Sobol2 = time.time()\n')
  f.write(f'model4Sobol2.fit(X_train_Sobol2, Y_train_Sobol2)\n')
  f.write(f'dt_Sobol2 = time.time() - t1_Sobol2\n')
  f.write(f'print(f\'ESS Kernel AFTER training: ')
  f.write('{kernel4} ')
  f.write('\')\n')
  f.write(f'print(f\'time for Sobol2, ESS Kernel: ')
  f.write('{dt_Sobol2')
  f.write('/3600}hrs\')\n')
  f.write(f'\n')
  f.write(f'\n')
  f.write(f'### evaluate models ###\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'Y_predictionGrid1296_mean_RBF, Y_predictionGrid1296_std_RBF = model1Grid1296.predict(X_test_Grid1296, return_std=True)\n')
  f.write(f'rmseGrid1296_RBF = np.sqrt(mean_squared_error(Y_test_Grid1296, Y_predictionGrid1296_mean_RBF))\n')
  f.write(f'r2Grid1296_RBF = r2_score(Y_test_Grid1296, Y_predictionGrid1296_mean_RBF)\n')
  f.write(f'print(f\'Grid1296, RBF Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid1296_RBF}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid1296_RBF}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionGrid1296_mean_Matern, Y_predictionGrid1296_std_Matern = model2Grid1296.predict(X_test_Grid1296, return_std=True)\n')
  f.write(f'rmseGrid1296_Matern = np.sqrt(mean_squared_error(Y_test_Grid1296, Y_predictionGrid1296_mean_Matern))\n')
  f.write(f'r2Grid1296_Matern = r2_score(Y_test_Grid1296, Y_predictionGrid1296_mean_Matern)\n')
  f.write(f'print(f\'Grid1296, Matern Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid1296_Matern}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid1296_Matern}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionGrid1296_mean_RQ, Y_predictionGrid1296_std_RQ = model3Grid1296.predict(X_test_Grid1296, return_std=True)\n')
  f.write(f'rmseGrid1296_RQ = np.sqrt(mean_squared_error(Y_test_Grid1296, Y_predictionGrid1296_mean_RQ))\n')
  f.write(f'r2Grid1296_RQ = r2_score(Y_test_Grid1296, Y_predictionGrid1296_mean_RQ)\n')
  f.write(f'print(f\'Grid1296, RQ Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid1296_RQ}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid1296_RQ}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionGrid1296_mean_ESS, Y_predictionGrid1296_std_ESS = model4Grid1296.predict(X_test_Grid1296, return_std=True)\n')
  f.write(f'rmseGrid1296_ESS = np.sqrt(mean_squared_error(Y_test_Grid1296, Y_predictionGrid1296_mean_ESS))\n')
  f.write(f'r2Grid1296_ESS = r2_score(Y_test_Grid1296, Y_predictionGrid1296_mean_ESS)\n')
  f.write(f'print(f\'Grid1296, ESS Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid1296_ESS}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid1296_ESS}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionGrid2401_mean_RBF, Y_predictionGrid2401_std_RBF = model1Grid2401.predict(X_test_Grid2401, return_std=True)\n')
  f.write(f'rmseGrid2401_RBF = np.sqrt(mean_squared_error(Y_test_Grid2401, Y_predictionGrid2401_mean_RBF))\n')
  f.write(f'r2Grid2401_RBF = r2_score(Y_test_Grid2401, Y_predictionGrid2401_mean_RBF)\n')
  f.write(f'print(f\'Grid2401, RBF Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid2401_RBF}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid2401_RBF}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionGrid2401_mean_Matern, Y_predictionGrid2401_std_Matern = model2Grid2401.predict(X_test_Grid2401, return_std=True)\n')
  f.write(f'rmseGrid2401_Matern = np.sqrt(mean_squared_error(Y_test_Grid2401, Y_predictionGrid2401_mean_Matern))\n')
  f.write(f'r2Grid2401_Matern = r2_score(Y_test_Grid2401, Y_predictionGrid2401_mean_Matern)\n')
  f.write(f'print(f\'Grid2401, Matern Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid2401_Matern}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid2401_Matern}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionGrid2401_mean_RQ, Y_predictionGrid2401_std_RQ = model3Grid2401.predict(X_test_Grid2401, return_std=True)\n')
  f.write(f'rmseGrid2401_RQ = np.sqrt(mean_squared_error(Y_test_Grid2401, Y_predictionGrid2401_mean_RQ))\n')
  f.write(f'r2Grid2401_RQ = r2_score(Y_test_Grid2401, Y_predictionGrid2401_mean_RQ)\n')
  f.write(f'print(f\'Grid2401, RQ Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid2401_RQ}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid2401_RQ}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionGrid2401_mean_ESS, Y_predictionGrid2401_std_ESS = model4Grid2401.predict(X_test_Grid2401, return_std=True)\n')
  f.write(f'rmseGrid2401_ESS = np.sqrt(mean_squared_error(Y_test_Grid2401, Y_predictionGrid2401_mean_ESS))\n')
  f.write(f'r2Grid2401_ESS = r2_score(Y_test_Grid2401, Y_predictionGrid2401_mean_ESS)\n')
  f.write(f'print(f\'Grid2401, ESS Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseGrid2401_ESS}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Grid2401_ESS}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol1_mean_RBF, Y_predictionSobol1_std_RBF = model1Sobol1.predict(X_test_Sobol1, return_std=True)\n')
  f.write(f'rmseSobol1_RBF = np.sqrt(mean_squared_error(Y_test_Sobol1, Y_predictionSobol1_mean_RBF))\n')
  f.write(f'r2Sobol1_RBF = r2_score(Y_test_Sobol1, Y_predictionSobol1_mean_RBF)\n')
  f.write(f'print(f\'Sobol1, RBF Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol1_RBF}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol1_RBF}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol1_mean_Matern, Y_predictionSobol1_std_Matern = model2Sobol1.predict(X_test_Sobol1, return_std=True)\n')
  f.write(f'rmseSobol1_Matern = np.sqrt(mean_squared_error(Y_test_Sobol1, Y_predictionSobol1_mean_Matern))\n')
  f.write(f'r2Sobol1_Matern = r2_score(Y_test_Sobol1, Y_predictionSobol1_mean_Matern)\n')
  f.write(f'print(f\'Sobol1, Matern Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol1_Matern}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol1_Matern}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol1_mean_RQ, Y_predictionSobol1_std_RQ = model3Sobol1.predict(X_test_Sobol1, return_std=True)\n')
  f.write(f'rmseSobol1_RQ = np.sqrt(mean_squared_error(Y_test_Sobol1, Y_predictionSobol1_mean_RQ))\n')
  f.write(f'r2Sobol1_RQ = r2_score(Y_test_Sobol1, Y_predictionSobol1_mean_RQ)\n')
  f.write(f'print(f\'Sobol1, RQ Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol1_RQ}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol1_RQ}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol1_mean_ESS, Y_predictionSobol1_std_ESS = model4Sobol1.predict(X_test_Sobol1, return_std=True)\n')
  f.write(f'rmseSobol1_ESS = np.sqrt(mean_squared_error(Y_test_Sobol1, Y_predictionSobol1_mean_ESS))\n')
  f.write(f'r2Sobol1_ESS = r2_score(Y_test_Sobol1, Y_predictionSobol1_mean_ESS)\n')
  f.write(f'print(f\'Sobol1, ESS Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol1_ESS}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol1_ESS}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol2_mean_RBF, Y_predictionSobol2_std_RBF = model1Sobol2.predict(X_test_Sobol2, return_std=True)\n')
  f.write(f'rmseSobol2_RBF = np.sqrt(mean_squared_error(Y_test_Sobol2, Y_predictionSobol2_mean_RBF))\n')
  f.write(f'r2Sobol2_RBF = r2_score(Y_test_Sobol2, Y_predictionSobol2_mean_RBF)\n')
  f.write(f'print(f\'Sobol2, RBF Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol2_RBF}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol2_RBF}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol2_mean_Matern, Y_predictionSobol2_std_Matern = model2Sobol2.predict(X_test_Sobol2, return_std=True)\n')
  f.write(f'rmseSobol2_Matern = np.sqrt(mean_squared_error(Y_test_Sobol2, Y_predictionSobol2_mean_Matern))\n')
  f.write(f'r2Sobol2_Matern = r2_score(Y_test_Sobol2, Y_predictionSobol2_mean_Matern)\n')
  f.write(f'print(f\'Sobol2, Matern Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol2_Matern}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol2_Matern}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol2_mean_RQ, Y_predictionSobol2_std_RQ = model3Sobol2.predict(X_test_Sobol2, return_std=True)\n')
  f.write(f'rmseSobol2_RQ = np.sqrt(mean_squared_error(Y_test_Sobol2, Y_predictionSobol2_mean_RQ))\n')
  f.write(f'r2Sobol2_RQ = r2_score(Y_test_Sobol2, Y_predictionSobol2_mean_RQ)\n')
  f.write(f'print(f\'Sobol2, RQ Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol2_RQ}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol2_RQ}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'Y_predictionSobol2_mean_ESS, Y_predictionSobol2_std_ESS = model4Sobol2.predict(X_test_Sobol2, return_std=True)\n')
  f.write(f'rmseSobol2_ESS = np.sqrt(mean_squared_error(Y_test_Sobol2, Y_predictionSobol2_mean_ESS))\n')
  f.write(f'r2Sobol2_ESS = r2_score(Y_test_Sobol2, Y_predictionSobol2_mean_ESS)\n')
  f.write(f'print(f\'Sobol2, ESS Kernel\')\n')
  f.write(f'print(f\'RMSE:') 
  f.write('{rmseSobol2_ESS}\')\n')
  f.write(f'print(f\'R2: ')
  f.write('{r2Sobol2_ESS}\')\n')
  f.write(f'print(f\'\\n\')\n')
  f.write(f'\n')
  f.write(f'\n')
  f.write(f'### save models ###\n')
  f.write(f'pickle.dump(model1Grid1296, open(\'trained_modelGrid1296_{ratio}_{rnd_int}_RBF.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model2Grid1296, open(\'trained_modelGrid1296_{ratio}_{rnd_int}_Matern.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model3Grid1296, open(\'trained_modelGrid1296_{ratio}_{rnd_int}_RQ.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model4Grid1296, open(\'trained_modelGrid1296_{ratio}_{rnd_int}_ESS.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model1Grid2401, open(\'trained_modelGrid2401_{ratio}_{rnd_int}_RBF.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model2Grid2401, open(\'trained_modelGrid2401_{ratio}_{rnd_int}_Matern.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model3Grid2401, open(\'trained_modelGrid2401_{ratio}_{rnd_int}_RQ.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model4Grid2401, open(\'trained_modelGrid2401_{ratio}_{rnd_int}_ESS.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model1Sobol1, open(\'trained_modelSobol1_{ratio}_{rnd_int}_RBF.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model2Sobol1, open(\'trained_modelSobol1_{ratio}_{rnd_int}_Matern.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model3Sobol1, open(\'trained_modelSobol1_{ratio}_{rnd_int}_RQ.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model4Sobol1, open(\'trained_modelSobol1_{ratio}_{rnd_int}_ESS.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model1Sobol2, open(\'trained_modelSobol2_{ratio}_{rnd_int}_RBF.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model2Sobol2, open(\'trained_modelSobol2_{ratio}_{rnd_int}_Matern.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model3Sobol2, open(\'trained_modelSobol2_{ratio}_{rnd_int}_RQ.sav\', \'wb\'))\n')
  f.write(f'pickle.dump(model4Sobol2, open(\'trained_modelSobol2_{ratio}_{rnd_int}_ESS.sav\', \'wb\'))\n')
  f.close()
  
  return os.path.basename(thisPythonFile)
  
  
### loop over ratios for testdata splits ###
for ratio in testsizes:
  #print(f'Ratio for Testdata Split: {ratio}')
  tmp_cwd = os.path.join(cwd, str(ratio))
  os.mkdir(tmp_cwd)
  os.chdir(tmp_cwd)
  #print(f'{os.getcwd()}')
  tmp_datasetfiles = copy_datasetfiles(tmp_cwd, datasetfiles)
  #print(f'{tmp_datasetfiles}')
  
  ## start a batch job for every rnd_int
  batchFiles = []
  for rnd_int in random_ints:
    #print(f'\trnd int: {rnd_int}')
    thisPythonFile = create_python_file(tmp_cwd, rnd_int, ratio, tmp_datasetfiles)
    thisBatchFile = create_batch_file(tmp_cwd, rnd_int, ratio, thisPythonFile)
    #print(f'{thisBatchFile}')
    batchFiles.append(thisBatchFile)
    #break

  executeScriptFile = 'put_everything_here_in_queue.sh'
  if os.path.exists(os.path.join(tmp_cwd, executeScriptFile)):
   os.remove(os.path.join(tmp_cwd, executeScriptFile))
  f = open(os.path.join(tmp_cwd, executeScriptFile), 'w')
  for batchFile in batchFiles:
    f.write(f'sbatch {batchFile}\n')
  f.close()
  
  os.popen(f'chmod +x {executeScriptFile}')
  print(f'Starting squeue for Testsplit ratio: {ratio}')
  os.popen(f'sh {executeScriptFile}')
  #break
